from django.db import models

import random
import string

# Create your models here.

def code_generator(size=10, chars=string.ascii_lowercase + string.ascii_uppercase):
    # new_code = ''
    # for i in range(size):
    #     new_code += random.choice(chars)
    # return new_code
    return ''.join(random.choice(chars) for i in range(size))

class ShortenURL(models.Model):
    url = models.CharField(max_length=250,)
    shorturl = models.CharField(max_length=15, unique=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    # if you already have some data with field and then you add another field in database
    # shorturl = models.CharField(max_length=15, null=True) # emty in database is ok
    # or
    # shorturl = models.CharField(max_length=15, default='abcd')
    # or you can delete database and regenerate

    def save(self, *args, **kwargs):
        self.shorturl = code_generator()
        super(ShortenURL, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.url)
    # this return function is to show the added data as a list on web app
    # to show the primary key or primary id
    # return str(self.id)
    # return str(self.pk)
    # id and pk will be autogenerated by django

    # for python2
    def __unicode__(self):
        return str(self.url)
