# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goshort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenurl',
            name='shorturl',
            field=models.CharField(default='abcd', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
